name: Run CodeQL Scan

on:
  workflow_dispatch:

jobs:
  code-scan:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Configure wolfSSL
      run: |
        ./autogen.sh
        ./configure --enable-all

